name: pullrequest

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git log -1
      - run: echo HEAD REF = ${{ github.head_ref }}

      - name: Check commits
        uses: vtavernier/github-workflows/actions/commitlint@463fff6e61c01fc139d544de20af9e80fdd6ee51
        with:
          lint-from: HEAD
          lint-to: ${{ github.head_ref }}